version: "3"

# DISCLAIMER: do not change service names willy nilly, dockerfiles depend on them 

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/code/app
      - .:/code
    ports: 
      - 8080:80
    environment:
      PYTHONPATH: /code/app/api/dependencies