host_ip: '10.0.0.253'
host_port: 8004
video_storage_root_path: 'c/Users/Peter/Desktop'
audio_storage_root_path: 'c/Users/Peter/Desktop'
asr_model_path: 'C:\Users\peter\Desktop\CharlesBot\external-services\speech-transcription\models\vosk-model-small-en-us-0.15'



# current transcription model path
# external ASR server port
# external intent classifier port
# intent_classifier_dir