host_ip: '10.0.0.2'
host_port: 8012
video_storage_root_path: 'C:\Users\Peter\Desktop\video'
audio_storage_root_path: 'C:\Users\Peter\Desktop\audio'
asr_model_path: r'C:\Users\peter\Desktop\CharlesBot\external-services\speech-transcription\models\vosk-model-small-en-us-0.15'
session_termination_token: '&&9&&'
immediate_repetion_token: '++'
external_speech_transcription_server_port: 8005


# yaml has functionality to run python code in .yaml files:
  # use that to dynamically get the host ip